version: clean_rnn_deterministic_hidden64_hardRestartWarmup

input_dim: 26
hidden_dim: 64
output_dim: 1
in_seq_len: 24
out_seq_len: 24
dropout: 0.1
scaling:
  H_MEAN: 208067.33730670897
  H_STD: 241361.16853850652
  C_MEAN: -227953.4075332571
  C_STD: 259908.86350470388
  H_TRIGGER_RATIO: 0.3159
  C_TRIGGER_RATIO: 0.4933
model_arch: RNN
loss: deterministic

batch_size: 128
num_epochs: 400
learning_rate: 1e-3
lr_warmup_epochs: 10